version: '3.7'

services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=apptnr
      - POSTGRES_PASSWORD=204rkmafd90-ad
    env_file: secrects.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - ipv6ula


  web:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://apptnr:204rkmafd90-ad@db/apptnr
      - VIRTUAL_HOST=mitgliedsantrag.bewegung.jetzt
      - LETSENCRYPT_HOST=mitgliedsantrag.bewegung.jetzt
      - LETSENCRYPT_EMAIL=domains@bewegung.jetzt
    env_file: secrects.env
    command: gunicorn -w 3 -b 0.0.0.0 appntr.wsgi
    volumes:
      - ./data/public:/code/public
    expose:
      - 8000
    links:
      - db
    networks:
      - ipv6ula

networks:
  ipv6ula:
    external: true
    name: ipv6ula
