# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('external_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('once', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField()),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='appntr.Interviewer')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='interview_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leading', to='appntr.Interviewer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='interview_snd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='appntr.Interviewer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appntr.Invite'),
        ),
    ]
