# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('new', 'new'), ('to_invite', 'To invite'), ('invited', 'Invited'), ('interview', 'Being interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=25)),
                ('first_name', models.CharField(max_length=255, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nachname')),
                ('gender', models.CharField(max_length=30, verbose_name='Geschlecht')),
                ('email', models.CharField(help_text='Unter welcher E-Mail Adresse können wir Dich persönlich erreichen?', max_length=255, verbose_name='E-Mail Adresse')),
                ('phone', models.CharField(help_text='Unter welcher Telefonnummer können wir Dich persönlich erreichen?', max_length=255, verbose_name='Telefonnummer')),
                ('country', models.CharField(help_text='In welchem Bundesland hast du deinen Erstwohnsitz?', max_length=25, verbose_name='Bundesland')),
                ('internet_profiles', models.TextField(blank=True, null=True, verbose_name='Falls vorhanden: Persönliche Webseite(n), Profile auf Sozialen Netzwerken (Xing, Facebook, Twitter und so weiter)')),
                ('motivation', models.TextField()),
                ('skills', models.TextField()),
                ('ethical_dilemma', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appntr.Application')),
                ('interview_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leading', to=settings.AUTH_USER_MODEL)),
                ('interview_snd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('reminded_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('application', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='appntr.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('once', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField()),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('vote', models.CharField(choices=[('y', 'yay'), ('n', 'nay'), ('a', 'abstain')], max_length=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='appntr.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together=set([('user', 'application')]),
        ),
    ]
