# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='external_url',
            field=models.CharField(max_length=1024),
        ),
    ]
