# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0002_auto_20170331_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='invite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appntr.Invite'),
        ),
    ]
