# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0003_userconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='affiliations',
            field=models.TextField(blank=True, null=True, verbose_name='Falls vorhanden: (ehemalige) Parteimitgliedschaft oder Interessenvertretungen'),
        ),
    ]
