# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0003_auto_20170331_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('inbox', 'Incoming'), ('anon_vote', 'In Voting (anon)'), ('person_vote', 'In Voting (person)'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('backburner', 'on Backburner')], default='inbox', max_length=25)),
                ('anon_name', models.CharField(max_length=255)),
                ('anon_content', models.TextField()),
                ('actual_name', models.CharField(max_length=255)),
                ('personal_content', models.TextField()),
                ('contact_details', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('trello_id', models.CharField(blank=True, max_length=25, null=True)),
                ('loomio_id', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
