# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0004_application_affiliations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='zoom_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
