# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0004_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfgOption',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
