# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0005_cfgoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='loomio_id',
            new_name='loomio_cur_proposal_id',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='trello_id',
            new_name='loomio_discussion_id',
        ),
    ]
