# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0006_auto_20170404_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfgoption',
            name='key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
