# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-11 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0006_application_marktplatz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contacted_members',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='dib_participation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='dib_participation_details',
            field=models.TextField(blank=True, help_text='Wenn ja, welche Aktionen hat Du bereits mitgemacht - bitte kurz aufzählen: (z.B. Initiative eingereicht, Unterschriften gesammelt, Stände betreut, DiB-Tische besucht etc.)', null=True),
        ),
    ]
