# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0007_dib_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contacted_members',
            field=models.TextField(blank=True, null=True, verbose_name='Falls gegeben: Ich bin bereits mit folgenden DiB-Aktiven im Kontakt:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dib_participation',
            field=models.BooleanField(default=False, verbose_name='Ich habe bereits an Aktionen von DiB teilgenommen'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dib_participation_details',
            field=models.TextField(blank=True, help_text='Bitte zähle kurz auf: (z.B. Initiative eingereicht, Unterschriften gesammelt, Stände betreut, DiB-Tische besucht etc.)', null=True, verbose_name='Wenn ja, welche Aktionen hat Du bereits mitgemacht:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='marktplatz_name',
            field=models.CharField(blank=True, help_text='Falls gegeben: Nutzername auf dem Marktplatz der Ideen', max_length=120, null=True, verbose_name='Marktplatz Nutzername'),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('to_invite', 'To invite'), ('invited', 'Invited'), ('interview', 'Being interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=25),
        ),
        migrations.AlterIndexTogether(
            name='application',
            index_together=set([('state',)]),
        ),
    ]
