# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0007_auto_20170404_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('inbox', 'Incoming'), ('anon_vote', 'In Voting (anon)'), ('person_vote', 'In Voting (person)'), ('to_invite', 'To invite'), ('invited', 'Invited'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('backburner', 'on Backburner')], default='inbox', max_length=25),
        ),
    ]
