# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-10 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0008_auto_20171130_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='country',
            field=models.CharField(help_text='In welchem Bundesland hast Du Deinen Erstwohnsitz?', max_length=25, verbose_name='Bundesland'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dib_participation_details',
            field=models.TextField(blank=True, help_text='Bitte zähle kurz auf: (z.B. Initiative eingereicht, Unterschriften gesammelt, Stände betreut, DiB-Tische besucht etc.)', null=True, verbose_name='Wenn ja, welche Aktionen hast Du bereits mitgemacht:'),
        ),
        migrations.AlterField(
            model_name='application',
            name='marktplatz_name',
            field=models.CharField(blank=True, help_text='Falls vorhanden: Nutzer*innen-Name auf dem Marktplatz der Ideen https://marktplatz.dib.de/', max_length=120, null=True, verbose_name='Marktplatz-Nutzer*innen-Name'),
        ),
    ]
