# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-13 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0009_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='interviewer_names',
            field=models.CharField(max_length=255, verbose_name='Namen der beiden DiB-Gesprächspartner*innen'),
        ),
    ]
