# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0010_auto_20170415_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='application',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appntr.Application'),
        ),
        migrations.AddField(
            model_name='invite',
            name='extra_info',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='external_url',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
