# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-13 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0010_auto_20180113_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('yes', 'Ja, aufnehmen'), ('no', 'Nein, nicht aufnehmen'), ('maybe', 'Wir können uns nicht einigen. Bitte erneut einladen.'), ('missed', 'Person ist nicht zum Termin erschienen'), ('recall_yes', 'Gespräch einzeln geführt, meine Empfehlung: ja, aufnehmen --> bitte zweiten Gesprächspartner organisieren'), ('recall_no', 'Gespräch einzeln geführt, meine Empfehlung: nein, nicht aufnehmen --> bitte zweiten Gesprächspartner organisieren'), ('recall_maybe', 'Gespräch einzeln geführt, meine Empfehlung:bin mir unsicher --> bitte zwei neue Gesprächspartner organisieren')], db_index=True, max_length=25, verbose_name='Rückmeldung'),
        ),
    ]
