# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-04 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0011_auto_20180113_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('open', 'offen'), ('done', 'erledigt')], default='open', max_length=255, verbose_name='Status'),
        ),
    ]
