# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0011_auto_20170509_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='actual_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='anon_content',
        ),
        migrations.RemoveField(
            model_name='application',
            name='anon_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='application',
            name='loomio_cur_proposal_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='loomio_discussion_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='personal_content',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='name',
        ),
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(default=' ', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='ethical_dilemma',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='internet_profiles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='motivation',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('to_invite', 'To invite'), ('invited', 'Invited'), ('interview', 'Being interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='interview_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leading', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='interview_snd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
