# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-04 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0012_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
