# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appntr', '0012_auto_20170613_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('vote', models.CharField(choices=[('y', 'yay'), ('n', 'nay'), ('a', 'abstain')], max_length=1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='appntr.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together=set([('user', 'application')]),
        ),
    ]
