# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-04 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appntr', '0013_feedback_done_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='done_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
