# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-27 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0014_feedback_done_user'),
        ('appntr', '0010_auto_20180511_0545'),
    ]

    operations = [
    ]
