# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-20 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appntr', '0015_merge_20190727_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='affiliations',
            field=models.TextField(blank=True, null=True, verbose_name='Falls vorhanden: (ehemalige) Parteimitgliedschaft(en) oder Interessenvertretungen'),
        ),
    ]
